global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'fastapi-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ai:8000']
