apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: cowrite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowrite-app
  template:
    metadata:
      labels:
        app: cowrite-app
    spec:
      containers:
      - name: app
        image: jakubzajkowski/cowrite-user-service:latest
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: cowrite-config
              key: APP_DATABASE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: cowrite-secrets
              key: postgres-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cowrite-secrets
              key: postgres-password
        - name: JWT_COOKIE_NAME
          valueFrom:
            configMapKeyRef:
              name: cowrite-config
              key: JWT_COOKIE_NAME
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: cowrite-secrets
              key: jwt-secret
        - name: JWT_EXPIRATION
          valueFrom:
            configMapKeyRef:
              name: cowrite-config
              key: JWT_EXPIRATION
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: cowrite-config
              key: SPRING_APPLICATION_NAME
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: cowrite-config
              key: SPRING_JPA_HIBERNATE_DDL_AUTO
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: cowrite
spec:
  selector:
    app: cowrite-app
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
